import { IProductItem } from "../types/ProductTypes";

export const productData: IProductItem[] = [
  {
    id: 1,
    name: "Tshirt 1",
    description: "",
    category: 1,
    ratings: 4,
    variants: [
      {
        id: 1,
        color: "red",
        size: "S",
        price: 100,
        images: [
          "https://shopping-all-images.s3.ap-southeast-2.amazonaws.com/1eedfc26b27ea1dd271ec71621e59c13.jpg",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 2,
        color: "blue",
        size: "S",
        price: 100,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 3,
        color: "green",
        size: "S",
        price: 100,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 4,
        color: "red",
        size: "M",
        price: 120,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 5,
        color: "blue",
        size: "M",
        price: 120,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 6,
        color: "green",
        size: "M",
        price: 120,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 7,
        color: "red",
        size: "L",
        price: 140,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 8,
        color: "blue",
        size: "L",
        price: 140,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 9,
        color: "green",
        size: "L",
        price: 140,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 10,
        color: "blue",
        size: "XL",
        price: 160,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 11,
        color: "green",
        size: "XL",
        price: 160,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Jeans",
    description: "",
    category: 1,
    ratings: 4,
    variants: [
      {
        id: 1,
        color: "red",
        size: "S",
        price: 100,
        images: [
          "https://shopping-all-images.s3.ap-southeast-2.amazonaws.com/heather-ford-5gkYsrH_ebY-unsplash.jpg",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 2,
        color: "blue",
        size: "S",
        price: 100,
        images: [
          "https://shopping-all-images.s3.ap-southeast-2.amazonaws.com/heather-ford-5gkYsrH_ebY-unsplash.jpg",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 3,
        color: "green",
        size: "S",
        price: 100,
        images: [
          "https://shopping-all-images.s3.ap-southeast-2.amazonaws.com/spring-wardrobe-switch-still-life.jpg",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 4,
        color: "red",
        size: "M",
        price: 120,
        images: [
          "https://shopping-all-images.s3.ap-southeast-2.amazonaws.com/still-life-spring-wardrobe-switch.jpg",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 5,
        color: "blue",
        size: "M",
        price: 120,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 6,
        color: "green",
        size: "M",
        price: 120,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 7,
        color: "red",
        size: "L",
        price: 140,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 8,
        color: "blue",
        size: "L",
        price: 140,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 9,
        color: "green",
        size: "L",
        price: 140,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 10,
        color: "blue",
        size: "XL",
        price: 160,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 11,
        color: "green",
        size: "XL",
        price: 160,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
    ],
  },
  {
    id: 3,
    name: "Pant",
    description: "",
    category: 1,
    ratings: 4,
    variants: [
      {
        id: 1,
        color: "red",
        size: "S",
        price: 100,
        images: [
          "https://shopping-all-images.s3.ap-southeast-2.amazonaws.com/heather-ford-5gkYsrH_ebY-unsplash.jpg",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 2,
        color: "blue",
        size: "S",
        price: 100,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 3,
        color: "green",
        size: "S",
        price: 100,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 4,
        color: "red",
        size: "M",
        price: 120,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 5,
        color: "blue",
        size: "M",
        price: 120,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 6,
        color: "green",
        size: "M",
        price: 120,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 7,
        color: "red",
        size: "L",
        price: 140,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 8,
        color: "blue",
        size: "L",
        price: 140,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 9,
        color: "green",
        size: "L",
        price: 140,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 10,
        color: "blue",
        size: "XL",
        price: 160,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 11,
        color: "green",
        size: "XL",
        price: 160,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
    ],
  },
  {
    id: 4,
    name: "Shoes",
    description: "",
    category: 1,
    ratings: 4,
    variants: [
      {
        id: 1,
        color: "red",
        size: "S",
        price: 100,
        images: [
          "https://shopping-all-images.s3.ap-southeast-2.amazonaws.com/spring-wardrobe-switch-still-life.jpg",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 2,
        color: "blue",
        size: "S",
        price: 100,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 3,
        color: "green",
        size: "S",
        price: 100,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 4,
        color: "red",
        size: "M",
        price: 120,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 5,
        color: "blue",
        size: "M",
        price: 120,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 6,
        color: "green",
        size: "M",
        price: 120,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 7,
        color: "red",
        size: "L",
        price: 140,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 8,
        color: "blue",
        size: "L",
        price: 140,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 9,
        color: "green",
        size: "L",
        price: 140,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 10,
        color: "blue",
        size: "XL",
        price: 160,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 11,
        color: "green",
        size: "XL",
        price: 160,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
    ],
  },
  {
    id: 5,
    name: "Purse",
    description: "",
    category: 1,
    ratings: 4,
    variants: [
      {
        id: 1,
        color: "red",
        price: 100,
        images: [
          "https://shopping-all-images.s3.ap-southeast-2.amazonaws.com/yasu-shots-_y6hMz1pJC0-unsplash.jpg",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 2,
        color: "blue",
        price: 100,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 3,
        color: "green",
        size: "S",
        price: 100,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 4,
        color: "red",
        size: "M",
        price: 120,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 5,
        color: "blue",
        size: "M",
        price: 120,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 6,
        color: "green",
        size: "M",
        price: 120,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 7,
        color: "red",
        size: "L",
        price: 140,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 8,
        color: "blue",
        size: "L",
        price: 140,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 9,
        color: "green",
        size: "L",
        price: 140,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 10,
        color: "blue",
        size: "XL",
        price: 160,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
      {
        id: 11,
        color: "green",
        size: "XL",
        price: 160,
        images: [
          "https://www.google.com",
          "https://www.google.com",
          "https://www.google.com",
        ],
      },
    ],
  },
];
